name: PHP Images

on:
  - push

jobs:
  build-base-images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        minor:
          - '7.4'
          - '7.3'
          - '7.2'
        patch:
          - '7.4.0'
          - '7.3.12'
          - '7.2.25'
        flavour:
          - 'cli'
          - 'fpm'

        # Manually exclude the miss-matching versions from the build matrix.
        # I really wish there was a better way to set this up.
        exclude:
          - { minor: '7.4', patch: '7.3.12' }
          - { minor: '7.4', patch: '7.2.25' }
          - { minor: '7.3', patch: '7.4.0' }
          - { minor: '7.3', patch: '7.2.25' }
          - { minor: '7.2', patch: '7.4.0' }
          - { minor: '7.2', patch: '7.3.12' }

    # Make sure the patch belongs to the minor.
    # A safety net assuming the above matrix exclude doesn't work.
    # This would work but matrix doesn't work here, its evaluated before the matrix is expanded.
    # https://github.community/t5/GitHub-Actions/Matrix-cannot-be-used-in-jobs-level-if/td-p/41048
#    if: startsWith(matrix.patch, matrix.minor)

    env:
      TAG_MINOR: 'musurp/php:${{ matrix.minor }}-${{ matrix.flavour }}'
      TAG_PATCH: 'musurp/php:${{ matrix.patch }}-${{ matrix.flavour }}'

    steps:
      - uses: actions/checkout@master

      - name: Build & Tag
        run: docker build --compress --tag="$TAG_MINOR" --tag="$TAG_PATCH" "php/${{ matrix.minor }}/${{ matrix.flavour }}"

      - name: 'Smoke Test: CLI'
        run: docker run --entrypoint "/bin/sh" "$TAG_MINOR" -c "php -v"
        if: matrix.flavour == 'cli'

      - name: 'Smoke Test: FPM'
        run: docker run --entrypoint "/bin/sh" "$TAG_MINOR" -c "php-fpm -v"
        if: matrix.flavour == 'fpm'

      # Only done for master branch.
      # Publish the image to docker hub.

      - name: 'Publish: Authenticate'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Patch Version'
        run: docker push "$TAG_PATCH"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Minor Version'
        run: docker push "$TAG_MINOR"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Logout'
        run: docker logout
        if: github.ref == 'refs/heads/master'
