name: PHP Images

on:
  - push

jobs:
  build-base-images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        minor:
          - '7.4'
          - '7.3'
          - '7.2'
        patch:
          - '7.4.1'
          - '7.3.13'
          - '7.2.26'
        target:
          - 'cli'
          - 'fpm'

        # Manually exclude the miss-matching versions from the build matrix.
        # Waiting for anchoring support so the duplication can be removed.
        exclude:
          - { minor: '7.4', patch: '7.3.13' }
          - { minor: '7.4', patch: '7.2.26' }
          - { minor: '7.3', patch: '7.4.1' }
          - { minor: '7.3', patch: '7.2.26' }
          - { minor: '7.2', patch: '7.4.1' }
          - { minor: '7.2', patch: '7.3.13' }

    # This would work but matrix doesn't work here, its evaluated before the matrix is expanded.
    # https://github.community/t5/GitHub-Actions/Matrix-cannot-be-used-in-jobs-level-if/td-p/41048
    # if: startsWith(matrix.patch, matrix.minor)

    env:
      TAG_MINOR: 'musurp/php:${{ matrix.minor }}-${{ matrix.target }}'
      TAG_PATCH: 'musurp/php:${{ matrix.patch }}-${{ matrix.target }}'

    steps:
      - uses: actions/checkout@master

      - name: 'Build & Tag'
        run: docker build --compress --tag="$TAG_MINOR" --tag="$TAG_PATCH" "php/${{ matrix.minor }}/${{ matrix.target }}"

      - name: 'Smoke Test: CLI'
        run: docker run --entrypoint "/bin/sh" "$TAG_MINOR" -c "php -v"
        if: matrix.target == 'cli'

      - name: 'Smoke Test: FPM'
        run: docker run --entrypoint "/bin/sh" "$TAG_MINOR" -c "php-fpm -v"
        if: matrix.target == 'fpm'

      # Only done for master branch.
      # Publish the image to docker hub.

      - name: 'Publish: Authenticate'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Patch Version'
        run: docker push "$TAG_PATCH"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Minor Version'
        run: docker push "$TAG_MINOR"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Logout'
        run: docker logout
        if: github.ref == 'refs/heads/master'

  build-xdebug-images:
    runs-on: ubuntu-latest

    needs:
      - build-base-images

    strategy:
      matrix:
        minor:
          - '7.4'
          - '7.3'
          - '7.2'
        patch:
          - '7.4.1'
          - '7.3.13'
          - '7.2.26'
        target:
          - 'cli'
          - 'fpm'

        # Manually exclude the miss-matching versions from the build matrix.
        # Waiting for anchoring support so the duplication can be removed.
        exclude:
          - { minor: '7.4', patch: '7.3.13' }
          - { minor: '7.4', patch: '7.2.26' }
          - { minor: '7.3', patch: '7.4.1' }
          - { minor: '7.3', patch: '7.2.26' }
          - { minor: '7.2', patch: '7.4.1' }
          - { minor: '7.2', patch: '7.3.13' }

    env:
      TAG_MINOR: 'musurp/php-dev:${{ matrix.minor }}-${{ matrix.target }}'
      TAG_PATCH: 'musurp/php-dev:${{ matrix.patch }}-${{ matrix.target }}'

    steps:
      - uses: actions/checkout@master

      - name: 'Build & Tag'
        run: docker build --compress --tag="$TAG_MINOR" --tag="$TAG_PATCH" "php/${{ matrix.minor }}/${{ matrix.target }}/xdebug"

      - name: 'Smoke Test: CLI'
        run: docker run --entrypoint "/bin/sh" "$TAG_MINOR" -c "php -v"
        if: matrix.target == 'cli'

      - name: 'Smoke Test: FPM'
        run: docker run --entrypoint "/bin/sh" "$TAG_MINOR" -c "php-fpm -v"
        if: matrix.target == 'fpm'

      # Only done for master branch.
      # Publish the image to docker hub.

      - name: 'Publish: Authenticate'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Patch Version'
        run: docker push "$TAG_PATCH"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Minor Version'
        run: docker push "$TAG_MINOR"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Logout'
        run: docker logout
        if: github.ref == 'refs/heads/master'

  build-flavour-images:
    runs-on: ubuntu-latest

    needs:
      - build-xdebug-images

    strategy:
      matrix:
        minor:
          - '7.4'
          - '7.3'
          - '7.2'
        patch:
          - '7.4.1'
          - '7.3.13'
          - '7.2.26'
        target:
          - 'cli'
        flavour:
          - 'supervisor'

        # Manually exclude the miss-matching versions from the build matrix.
        # Waiting for anchoring support so the duplication can be removed.
        exclude:
          - { minor: '7.4', patch: '7.3.13' }
          - { minor: '7.4', patch: '7.2.26' }
          - { minor: '7.3', patch: '7.4.1' }
          - { minor: '7.3', patch: '7.2.26' }
          - { minor: '7.2', patch: '7.4.1' }
          - { minor: '7.2', patch: '7.3.13' }

    env:
      TAG_MINOR: 'musurp/php:${{ matrix.minor }}-${{ matrix.target }}-${{ matrix.flavour }}'
      TAG_PATCH: 'musurp/php:${{ matrix.patch }}-${{ matrix.target }}-${{ matrix.flavour }}'

    steps:
      - uses: actions/checkout@master

      - name: 'Build & Tag'
        run: docker build --compress --tag="$TAG_MINOR" --tag="$TAG_PATCH" "php/${{ matrix.minor }}/${{ matrix.target }}/${{ matrix.flavour }}"

      - name: 'Smoke Test: CLI'
        run: docker run --entrypoint "/bin/sh" "$TAG_MINOR" -c "php -v"
        if: matrix.target == 'cli'

      - name: 'Smoke Test: FPM'
        run: docker run --entrypoint "/bin/sh" "$TAG_MINOR" -c "php-fpm -v"
        if: matrix.target == 'fpm'

      # Only done for master branch.
      # Publish the image to docker hub.

      - name: 'Publish: Authenticate'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Patch Version'
        run: docker push "$TAG_PATCH"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Minor Version'
        run: docker push "$TAG_MINOR"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Logout'
        run: docker logout
        if: github.ref == 'refs/heads/master'

  build-flavour-xdebug-images:
    runs-on: ubuntu-latest

    needs:
      - build-flavour-images

    strategy:
      matrix:
        minor:
          - '7.4'
          - '7.3'
          - '7.2'
        patch:
          - '7.4.1'
          - '7.3.13'
          - '7.2.26'
        target:
          - 'cli'
        flavour:
          - 'supervisor'

        # Manually exclude the miss-matching versions from the build matrix.
        # Waiting for anchoring support so the duplication can be removed.
        exclude:
          - { minor: '7.4', patch: '7.3.13' }
          - { minor: '7.4', patch: '7.2.26' }
          - { minor: '7.3', patch: '7.4.1' }
          - { minor: '7.3', patch: '7.2.26' }
          - { minor: '7.2', patch: '7.4.1' }
          - { minor: '7.2', patch: '7.3.13' }

    env:
      TAG_MINOR: 'musurp/php-dev:${{ matrix.minor }}-${{ matrix.target }}-${{ matrix.flavour }}'
      TAG_PATCH: 'musurp/php-dev:${{ matrix.patch }}-${{ matrix.target }}-${{ matrix.flavour }}'

    steps:
      - uses: actions/checkout@master

      - name: 'Build & Tag'
        run: docker build --compress --tag="$TAG_MINOR" --tag="$TAG_PATCH" "php/${{ matrix.minor }}/${{ matrix.target }}/xdebug/${{ matrix.flavour }}"

      - name: 'Smoke Test: CLI'
        run: docker run --entrypoint "/bin/sh" "$TAG_MINOR" -c "php -v"
        if: matrix.target == 'cli'

      - name: 'Smoke Test: FPM'
        run: docker run --entrypoint "/bin/sh" "$TAG_MINOR" -c "php-fpm -v"
        if: matrix.target == 'fpm'

      # Only done for master branch.
      # Publish the image to docker hub.

      - name: 'Publish: Authenticate'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Patch Version'
        run: docker push "$TAG_PATCH"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Minor Version'
        run: docker push "$TAG_MINOR"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Logout'
        run: docker logout
        if: github.ref == 'refs/heads/master'
