name: PHP Images

on:
  - push

jobs:
  build-base-images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        minor:
          - '7.4'
          - '7.3'
          - '7.2'
        patch:
          - '7.4.0'
          - '7.3.12'
          - '7.2.25'
        flavour:
          - 'cli'
          - 'fpm'

    # Make sure we are only dealing with combinations of the same minor and patch versions.
    if: startsWith(matrix.patch, matrix.minor)

    env:
      TAG_MINOR: 'musurp/php:${{ matrix.minor }}-${{ matrix.flavour }}'
      TAG_PATCH: 'musurp/php:${{ matrix.patch }}-${{ matrix.flavour }}'

    steps:
      - uses: actions/checkout@master

      - name: Build & Tag
        run: docker build --compress --tag="$TAG_MINOR" --tag="$TAG_PATCH" "php/${{ matrix.minor }}/${{ matrix.flavour }}"

      - name: 'Smoke Test: CLI'
        run: docker run -it "$TAG_MINOR" sh -c "php -v"
        if: matrix.flavour == 'cli'

      - name: 'Smoke Test: FPM'
        run: docker run -it "$TAG_MINOR" sh -c "php-fpm -v"
        if: matrix.flavour == 'fpm'

      # Only done for master branch.
      # Publish the image to docker hub.

      - name: 'Publish: Authenticate'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Patch Version'
        run: docker push "$TAG_PATCH"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Minor Version'
        run: docker push "$TAG_MINOR"
        if: github.ref == 'refs/heads/master'

      - name: 'Publish: Logout'
        run: docker logout
        if: github.ref == 'refs/heads/master'
